### ISSUE TITLE
発表するための資料作り

### ISSUE THREAD

**Issue by shinseitaro** [fintalk/reading-How-to-Make-Money-in-Stocks#36]
### 概要
- チャプター９章完了後、勉強した内容をまとめてFintalkで発表するための資料を作る
- 資料を読めば、この本の内容と、実際取引をする時のチャートの見方や、決算情報の見方がすぐにわかるような内容が望ましい。
  - 具体的には、**Fintalkのメンバーで、初めて株式トレードをする人が、どのように銘柄を選び、どのタイミングでエントリーして、クローズすればよいか**、を示せる内容
- このIssueのコメントで、どのようにまとめて行くかを議論したい
- 資料作成完了予定日：**2022/03/27（3月最終日曜）**
- 発表予定日：**2022/05/14（土）**

### クローズ要件
- 資料作成

### チェックリスト

- [ ] 発表は、ZennのBook機能を使う。
  - [x] #39

**Comment by shinseitaro** [comment]
- 発表日を決定して、まずは今やっている各自のまとめを終わらせる？
- 何月くらいにおわれるか？コメントに書いてください。

**Comment by nobolis** [comment]
- 各節の長さ次第ですが、3月まではかかるかもです
- 年度末・年度初めは色々と書類仕事が増えるので、発表は5月以降だとうれしいです

**Comment by mikkegt** [comment]
2月中に終わらせます！

**Comment by shinseitaro** [comment]
では、発表は5月、まとめは3月をターゲットにしましょう！

**Comment by shinseitaro** [comment]
## 各章を 発表資料としてまとめ直すためのアイデア

**対象**： 「Fintalkのメンバーで初めて株式トレードをする人が、どのように銘柄を選び、どのタイミングでエントリーして、クローズすればよいか、を示せる内容」を各章でまとめて発表

- Chapter 毎に担当を決める？
  - 担当になった人が、**5分**で各章のポイントを伝える内容にまとめる。この内容はそのままZenn Bookに掲載する。
    - Github ／ [Zenn のスクラップ](https://zenn.dev/shinseitaro/scraps/db7e6e297077bf) 
  - 他の人も各章のノートをしっかり読んだ上で、レビューを行う。
- 本の内容をベースにハンズオンを行う？

**Comment by shinseitaro** [comment]
- Chapter によってはボリュームが大きく異なるので、Chapter 毎に行ってもいいが、最終的にはページ数などで調整
- 例えば２章はボリュームがあるので２章を担当した人とは、あと一つだけ担当するとか。
- チャプターの中で分けるよりは、１チャプターは一人が担当したほうが作業しやすいかな？と思ったんですがどうでしょう？

**Comment by shinseitaro** [comment]
- #39 を @Mikkegt さんにお願いしているので、そのぶんみさとさんのチャプター担当は減らしたほうがいいと思いました。

**Comment by shinseitaro** [comment]
- もしくは、結局２章(cup with handle) の回をわかっていればいいのでは？と割り切って、そこを中心にまとめて発表を行い、私達がここに残したものをZennに移す、というまとめでもいいかも？

**Comment by shinseitaro** [comment]
## zenn bookの運用方法

### 役割
@shinseitaro と @Mikkegt さんは、Zennブランチ管理。
@nobolis さんと @natsukoa さんは今まで通り、main にプッシュ

### 方法
1. 各自、現段階のmainからブランチを切ってノートを読み、修正加筆等加えていく
2. マージする前に変更点をみんなで共有する
3. main にマージ
4. zenn の book ディレクトリに、管理者二人が載せる
5. リリース
6. フィントークで発表 #42

**Comment by shinseitaro** [comment]
`review_shinseitaro` ブランチを、レビュー用に切りました
